# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evander Batson
email: evanderbatson@gmail.com
description: Design Portfolio of Evander Batson
myName: Evander Batson
baseurl: "/portfolio"
url: "http://evanderbatson.com" # the base hostname & protocol for your site
permalink: none

artPortfolio: evanderbatson
twitterUsername: smallweasel
githubUsername:  evanderbatson
instaUsername: evanderbatson
elloUsername: evander

# Build settings
markdown: kramdown
